server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
      register-with-eureka: true
      fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway:  DEBUG
    reactor.netty.http.client:  DEBUG

spring:
  application:
    name: infraestructure-apigateway
  cloud:
    gateway:
      routes:

      - id: sellout_service
        uri: lb://business-sellout
        predicates:
        - Path=/api/fybeca/**, /api/deprati/**

      - id: keycloak_service
        uri: lb://infraestructure-keycloak
        predicates:
        - Path=/api/security/**
